backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/media"
public_folder: "/media"

collections:
  - label: "Posts"
    name: "posts"
    folder: "src/content/posts"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Header Text", name: "headerText", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Authors"
    name: "authors"
    folder: "src/content/authors"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"} 

  - label: "Products"
    name: "products"
    folder: "src/content/products"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Header Text", name: "headerText", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Site Settings"
    name: "site"
    files:
      - label: "About Us"
        name: "about"
        file: "src/site/about.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image, required: false}
      - label: "Locations"
        name: "locations"
        file: "src/site/locations.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}

      - label: "Configuration"
        name: "config"
        file: "src/site/config.json"
        fields:
          - {label: "Copyright Statement", name: copyright,widget: string, required: false}
          - {label: "Google Analytics Tag ID", name: gaTagId, widget: string, required: false}